In [ ]:
import numpy as np
print(np.__version__)

1.26.4


In [ ]:
import numpy as np
A1=np.array([1,2,3,4])
print(A1)

[1 2 3 4]


In [ ]:
type(A1)

numpy.ndarray

In [ ]:
A1.shape

(4,)

In [ ]:
A2=np.array([[1,2,3,4],[5,6,7,8]])
print(A2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
type(A2)

numpy.ndarray

In [ ]:
A2.shape

(2, 4)

In [ ]:
A2.size

8

In [ ]:
A2.ndim

2

In [ ]:
A3=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(A3)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [ ]:
type(A3)

numpy.ndarray

In [ ]:
import numpy as np
np.ndarray

numpy.ndarray

In [ ]:
A3.shape

(2, 2, 4)

In [ ]:
A3.size

16

In [ ]:
A3.ndim

3

In [ ]:
import numpy as np
z1=np.zeros(3)
z1

array([0., 0., 0.])

In [ ]:
z1=np.zeros(3,dtype=int)
z1

array([0, 0, 0])

In [ ]:
z1.shape

(3,)

In [ ]:
z1.size

3

In [ ]:
z1.ndim

1

In [ ]:
type(z1)

numpy.ndarray

In [ ]:
z2=np.zeros((3,4),dtype=int)
z2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
z2.size

12

In [ ]:
z2.shape

(3, 4)

In [ ]:
z2.ndim

2

In [ ]:
z3=np.zeros((2,3,4))
z3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
z3.size

24

In [ ]:
z3.shape

(2, 3, 4)

In [ ]:
z3.ndim

3

In [ ]:
import numpy as np
a1=np.ones(3)
a1

array([1., 1., 1.])

In [ ]:
type(a1)

numpy.ndarray

In [ ]:
a1.size

3

In [ ]:
a1.shape

(3,)

In [ ]:
a1.ndim

1

In [ ]:
a2=np.ones([3,4])
a2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
type(a2)

numpy.ndarray

In [ ]:
a2.size

12

In [ ]:
a2.shape

(3, 4)

In [ ]:
a2.ndim

2

In [ ]:
a3=np.ones([4,2,3])
a3

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
type(a3)

numpy.ndarray

In [ ]:
a3.shape

(4, 2, 3)

In [ ]:
a3.size

24

In [ ]:
a3.ndim

3

In [ ]:
f1=np.full(3,9)
f1

array([9, 9, 9])

In [ ]:
f2=np.full([2,3],9)
f2

array([[9, 9, 9],
       [9, 9, 9]])

In [ ]:
f3=np.full([4,2,3],10)
f3

array([[[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]]])

In [ ]:
a=np.array([5,10,15])
b=np.array([4,6,8])
add=np.add(a,b)
add

array([ 9, 16, 23])

In [ ]:
a=np.array([5,10,15])
b=np.array([4,6,8])
subtract=np.subtract(a,b)
subtract

array([1, 4, 7])

In [ ]:
a=np.array([5,10,15])
b=np.array([4,6,8])
multiply=np.multiply(a,b)
multiply

array([ 20,  60, 120])

In [ ]:
a=np.array([5,10,15])
b=np.array([4,6,8])
divide=np.divide(a,b)
divide

array([1.25      , 1.66666667, 1.875     ])

In [ ]:
a=np.array([5,10,15])
b=np.array([4,6,8])
power=np.power(a,b)
power

array([       625,    1000000, 2562890625])

In [ ]:
a=np.array([5,10,15])
b=np.array([4,6,8])
mod=np.mod(a,b)
mod

array([1, 4, 7])